name: URLTEST

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0/2 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git config
      run: git config --local user.name "GitHub Actions"; git config --local user.email "actions@github.com"
    
    - name: Checkout private repository
      uses: actions/checkout@v4
      with:
        repository: dowment/pwcd
        token: ${{ secrets.privates }}
        path: pwc

    - name: Change directory and run pipeline.py
      run: |
        cd pwc
        python pipeline.py

    - name: Checkout this repository
      uses: actions/checkout@v4
      with:
        repository: dowment/run
        token: ${{ secrets.privates }}
        path: actions

    - name: Copy Clash.yml
      run: |
        pwd
        cd actions && pwd
        cp ../pwc/Clash.yml ./Clash.yml
        cp ../pwc/singbox*.json ./

    # - name: Remove pwc directory
    #   run: rm -rf pwc

    - name: Commit and push
      run: |
        pwd
        cd actions
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git pull origin main
        git merge main
        git add .
        git commit -m "$(date '+%Y.%m.%d %H:%M:%S') update"
        git push origin main

    - name: Commit and push to pwc repository
      run: |
        cd pwc
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        if [[ `git status --porcelain` ]]; then
          git pull origin main
          git merge main
          git add .
          git commit -m "$(date '+%Y.%m.%d %H:%M:%S') update"
          git push origin main
        else
          echo "No changes to commit"
        fi

